### ISSUE TITLE
Malformed Response Data

### ISSUE THREAD

**Issue by chris-prener** [slu-openGIS/censusxy#13] opened 2020-02-09 20:37 UTC
hey @bransonf - I've been working with some particularly exciting address data, and managed to break `censusxy`. With the attached data, I load them up in `R` and then:

```r
censusxy::cxy_geocode(test2, address = "gw_i_address", city = "gw_i_city",
            state  = "gw_i_state", zip = "gw_i_zip",
            style = "minimal", output = "tibble", timeout = 30)
```

This results in a warning:

```r
Warning message:
Expected 4 pieces. Missing pieces filled with `NA` in 3 rows [21, 33, 42]. 
```

When you look at what gets returned by commenting out lines 144 to 156 of `cxy_geocode.R`, you'll see that things aren't being put back where we expect them to be:

![image](https://user-images.githubusercontent.com/13595578/74109430-0b26a800-4b49-11ea-97d4-8978caaf886e.png)

Can you take a shot at figuring out what is causing the unexpected response?

[test2.zip](https://github.com/slu-openGIS/censusxy/files/4177790/test2.zip)

**Comment by bransonf** [comment] 2020-02-09 21:57
That warning message may have to do with what we resolved with the `tidyr::separate()` but won't know until the bigger issue is corrected.

And the issue is that something has apparently changed with the API. The actual CSV returned by the census bureau is not in the same format. So, the issue happens [here](https://github.com/slu-openGIS/censusxy/blob/f260503d92f19c4d30561331a33bd34023fd3f37/R/cxy_geocoder.R#L26)

Should be able to push a fix later tonight, early tomorrow

**Comment by chris-prener** [comment] 2020-02-09 22:21
I'm thinking they're related, because I only get the warning with these data and not others.

I also ran into a separate (but equally fun issue) - when the composite geocoder doesn't have any positive hits with `censusxy` it also has a funny outcome. I can figure that out I think, though. Will need you to school me on the census bureau's API in May before you graduate...

**Comment by bransonf** [comment] 2020-02-10 18:46
So the exact issue is this:

The rows in the returned CSV are of differing lengths. For `No_Match` there are 3 columns. For `Match` there are 12 columns. `read.csv()` OR `read_csv()` make guesses based on a sample of the data, and with this many non-matches, guess that 3 columns is appropriate. It explains why we didn't catch this when geocoding good data (mostly matches).

Here's where it gets interesting... The online download returns 12 columns, but the API returns 9-columns. We can force the number of columns, which is actually beneficial even if we get no matches, because it will standardize the dims of our data frame. (Removes like 8 lines of code)

Stumbled across actual [documentation](https://geocoding.geo.census.gov/geocoder/Geocoding_Services_API.pdf) which I didn't have when I first wrote this.

The best solution is a rewrite using a json response and building my own parser (json to data.frame) This is probably the most time consuming (a couple of hours) but it will remove our dependency on `tidyr` completely, reduce error proneness, and we can add an argument for geocoding to census geometries (Issue #4)

Further caveat being that we will probably break any existing use of the package, unless we try to rigorously match the current output (more time consuming).

I want to totally rewrite this, and reasonably I could do it sometime this week. Tell me why this is a bad idea.

**Comment by chris-prener** [comment] 2020-02-11 15:03
Yikes - OK - lets talk about this today!

**Closed** 2020-04-09 21:18 UTC
