### ISSUE TITLE
tie

### ISSUE THREAD

**Issue by overmar** [slu-openGIS/censusxy#26] opened 2020-09-28 16:10 UTC
From what I can tell when cxy_status = 'Tie' no geocode is listed, though it would make sense that there are two results. Is there a way to get at least one of those results to show up?

**Comment by chris-prener** [comment] 2020-09-28 20:08
hi @overmar - can you give us an example address that results in a tie?

**Comment by atorgerson** [comment] 2020-12-17 22:58
While trying to come up with a reproducible example of this, I came across some odd behavior. Re-submitting "tied" addresses to the batch geocoding endpoint often yields different results.

For example: I submitted 61,600 records to the batch geocoding endpoint and 506 returned with `cxy_status == "Tie"`. If I resubmit those 506 records with the same parameters to `cxy_geocode()`, some match, some don't match, and some tie, but the results are different every time. Unfortunately, my dataset is confidential, but here's my code and the results of five consecutive attempts at re-geocoding the 506 tied addresses.

```
library(tidyverse)
library(censusxy)

previous_results <- read_rds("data/processed/records_geocoded.rds")

tied_records <- 
  previous_results %>%
  filter(cxy_status == "Tie") %>%
  select(record_id, address, city, state, zip_5)

# previous_results was generated using identical parameters to cxy_geocode()
new_results <- 
  censusxy::cxy_geocode(
    tied_records, id = "record_id", street = "address", city = "city", 
    state = "state", zip = "zip_5", return = "geographies", 
    benchmark = "Public_AR_Current", vintage = "Current_Current", 
    class = "dataframe", output = "full"
  )

new_results %>% 
  count(cxy_status)
```

| cxy_status | Attempt 1 | Attempt 2 | Attempt 3 | Attempt 4 | Attempt 5 |
|-------------|-----------:|-------------:|-----------:|------------:|------------:|
| Match        | 33            | 269             | 201          | 34              | 187          |   
| No_Match | 22             | 0                 | 0              | 22              | 4              |
| Tie             | 451           | 237             | 305          | 450            | 315          | 
| Total          | 506           | 506             | 506          | 506            | 506          |

Frustratingly, if I try to create a reprex with just a few (n = 5), of the tied addresses, all of them come back matched every single time.

**Comment by chris-prener** [comment] 2020-12-17 23:19
Thanks for the super detailed reprex! I'm 99.9% sure this is an issue with the API itself and not the package, which does little to help you at. Can you replicate the issue on the [web interface](https://geocoding.geo.census.gov)? 

One additional thought are to try setting specific, prior [benchmark](https://slu-opengis.github.io/censusxy/reference/cxy_benchmarks.html) and [vintage](https://slu-opengis.github.io/censusxy/reference/cxy_vintages.html) values. I'm wondering if this is an issue with the current ones?

**Comment by chris-prener** [comment] 2020-12-17 23:20
Also, @bransonf - is this behavior you've seen before?

**Comment by bransonf** [comment] 2020-12-18 00:59
@chris-prener The crux of the issue for @atorgerson is that the `return = 'geographies'` feature is largely unreliable both via the web interface *and* API. As you suspect, it's an issue with the Census Bureau's implementation (or ESRI's fault). Changing benchmark and vintage was not fruitful in my testing months ago and I doubt this has changed since.

Maybe less than ideal, but one solution is to use `return = 'locations'` and calculate an intersection with the preferred geography.

Another less than ideal solution is to take the response lat,lon from `cxy_geocode()` and iterate these with `cxy_geography()`. However, this will still fail sporadically.

As for the current tie behavior, I don't have any available test cases. If I recall correctly, the batch interface doesn't return coordinates for ties (could be wrong, but don't have a test case). However, using either `cxy_single()` or `cxy_oneline()` should return all of the candidates.

**Comment by chris-prener** [comment] 2020-12-18 01:15
Thanks @bransonf - @atorgerson - I think the advice to return `locations` and then intersect is really solid. Happy to provide advice over email if you need any. Otherwise, I'm going to close this since its not an issue with the package per se.

**Closed by chris-prener** 2020-12-18 01:15 UTC

**Comment by bransonf** [comment] 2020-12-18 01:29
@atorgerson Feel free to email me as well. I suspect we already have a legal agreement in place to share data if necessary.
